# Generated by Django 4.0.1 on 2024-03-16 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_leave'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='enddate',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='leave',
            old_name='startdate',
            new_name='start_date',
        ),
    ]
