# Generated by Django 4.0.1 on 2024-03-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_leave_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='SUBJECT',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='TIMETABLE',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='time',
        ),
        migrations.AddField(
            model_name='attendance',
            name='hour',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(default='', max_length=20),
        ),
    ]
