# Generated by Django 4.0.1 on 2024-03-28 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_attendance_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='period',
            field=models.CharField(default='', max_length=20),
        ),
    ]
