# Generated by Django 4.0.1 on 2024-04-11 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_attendance_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='subwise_attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=30)),
                ('subject_name', models.CharField(max_length=30)),
                ('att', models.CharField(max_length=10)),
            ],
        ),
    ]
