
from django.contrib import admin
from django.urls import path

from myapp import views

urlpatterns = [
    path('login/', views.login),
    path('logout/', views.logout),
    path('login_post/',views.login_post),
    path('view_dept/', views.view_dept),
    path('view_dept_post/',views.view_dept_post),
    path('admin_home/', views.admin_home),
    path('add_dept/', views.add_dept),
    path('add_dept_post/', views.add_dept_post),
    path('edit_dept/<id>', views.edit_dept),
    path('edit_dept_post/', views.edit_dept_post),
    path('delete_dept/<id>', views.delete_dept),
    path('view_course/', views.view_course),
    path('view_course_post/', views.view_course_post),
    path('add_course/', views.add_course),
    path('add_course_post/', views.add_course_post),
    path('edit_course/<id>', views.edit_course),
    path('edit_course_post/', views.edit_course_post),
    path('delete_course/<id>', views.delete_course),
    path('view_subject/', views.view_subject),
    path('view_subject_post/', views.view_subject_post),
    path('add_subject/', views.add_subject),
    path('add_subject_post/', views.add_subject_post),
    path('edit_subject/<id>',views.edit_subject),
    path('edit_subject_post/',views.edit_subject_post),
    path('delete_subject/<id>',views.delete_subject),
    path('view_staff/',views.view_staff),
    path('view_staff_post/',views.view_staff_post),
    path('add_staff/', views.add_staff),
    path('add_staff_post/', views.add_staff_post),
    path('edit_staff/<id>',views.edit_staff),
    path('edit_staff_post/',views.edit_staff_post),
    path('delete_staff/<id>',views.delete_staff),
    path('reg/', views.reg),
    path('view_student/', views.view_student),
    path('view_student_post/', views.view_student_post),
    path('add_student/', views.add_student),
    path('add_student_post/', views.add_student_post),
    path('edit_student/<id>', views.edit_student),
    path('edit_student_post/', views.edit_student_post),
    path('delete_student/<id>',views.delete_student),
    path('hod_home/', views.hod_home),
    path('hod_view_subject/', views.hod_view_subject),
    path('hod_view_subject_post/', views.hod_view_subject_post),
    path('hod_add_subject/', views.hod_add_subject),
    path('hod_add_subject_post/', views.hod_add_subject_post),
    path('hod_edit_subject/<id>',views.hod_edit_subject),
    path('hod_edit_subject_post/',views.hod_edit_subject_post),
    path('hod_delete_subject/<id>',views.hod_delete_subject),
    path('hod_view_student/', views.hod_view_student),
    path('hod_view_student_post/', views.hod_view_student_post),
    path('hod_add_student/', views.hod_add_student),
    path('hod_add_student_post/', views.hod_add_student_post),
    path('hod_edit_student/<id>',views.hod_edit_student),
    path('hod_edit_student_post/',views.hod_edit_student_post),
    path('hod_delete_student/<id>',views.hod_delete_student),
    path('view_profile/',views.view_profile),
    path('view_profile_post/',views.view_profile_post),
    path('edit_profile/', views.edit_profile),
    path('edit_profile_post/', views.edit_profile_post),
    path('add_timetable/', views.add_timetable),
    path('addsubcheck/', views.addsubcheck),
    path('addstudcheck/', views.addstudcheck),
    path('add_timetable/', views.add_timetable),
    path('add_timetable_post/', views.add_timetable_post),
    path('view_timetable/', views.view_timetable),
    path('view_timetable_post/', views.view_timetable_post),
    path('staff_home/',views.staff_home),
    path('staff_view_timetable/',views.staff_view_timetable),
    path('staff_view_timetable_post/',views.staff_view_timetable_post),
    path('edit_timetable/<id>',views.edit_timetable),
    path('edit_timetable_post/',views.edit_timetable_post),
    path('delete_timetable/', views.delete_timetable),
    path('staff_view_student/', views.staff_view_student),
    path('staff_view_student_post/', views.staff_view_student_post),
    path('staff_view_subject/', views.staff_view_subject),
    path('staff_view_subject_post/', views.staff_view_subject_post),
    path('staff_view_profile/',views.staff_view_profile),
    path('staff_view_profile_post/',views.staff_view_profile_post),
    path('staff_edit_profile/',views.staff_edit_profile),
    path('staff_edit_profile_post/',views.staff_edit_profile_post),
    path('user_loginpost/',views.user_loginpost),
    path('user_viewprofile/',views.user_viewprofile),
    path('parent_viewprofile/',views.parent_viewprofile),
    path('user_change_password/',views.user_change_password),
    path('staff_view/',views.staff_view),
    path('leave_request/',views.leave_request),
    path('staff_view_leave/',views.staff_view_leave),
    path('staff_view_leave_post/',views.staff_view_leave_post),
    path('staff_leave_history/',views.staff_leave_history),
    path('staff_leave_history_post/',views.staff_leave_history_post),
    path('approve_leave/<id>',views.approve_leave),
    path('reject_leave/<id>',views.reject_leave),
    path('User_sendchat/',views.User_sendchat),
    path('User_viewchat/',views.User_viewchat),
    path('view_staff_chat/',views.view_staff_chat),
    path('chat/<id>',views.chat),
    path('view_parentchat/',views.view_parentchat),
    path('chat_view/',views.chat_view),
    path('chat_send/<msg>',views.chat_send),
    path('forget_password/',views.forget_password),
    path('student_view_attendance/',views.student_view_attendance),
    path('hod_view_attendance/',views.hod_view_attendance),
    path('hod_view_attendance_post/',views.hod_view_attendance_post),
    path('staff_view_attendance/',views.staff_view_attendance),
    path('staff_view_attendance_post/',views.staff_view_attendance_post),
    path('leave_history/',views.leave_history),
    path('hod_view_parentchat/',views.hod_view_parentchat),
    path('attendance_month/',views.attendance_month),
    path('attendance_month_post/',views.attendance_month_post),
    path('hod_attendance_total/',views.hod_attendance_total),
    path('hod_attendance_total_post/',views.hod_attendance_total_post),
    path('staff_attendance_month/',views.staff_attendance_month),
    path('staff_attendance_month_post/',views.staff_attendance_month_post),
    path('attendance_subject/',views.attendance_subject),
    path('attendance_subject_post/',views.attendance_subject_post),
    path('staff_attendance_subject/',views.staff_attendance_subject),
    path('staff_attendance_subject_post/',views.staff_attendance_subject_post),
    path('student_attendance_month/',views.student_attendance_month),
    path('student_attendance_total/',views.student_attendance_total),
    path('student_attendance_subject/',views.student_attendance_subject),
    path('generate_attendance/',views.generate_attendance),
    path('generate_report/',views.generate_report),
    path('generate_report_total/',views.generate_report_total),
    path('generate_attendance_total/',views.generate_attendance_total),
    path('generate_report_month/',views.generate_report_month),
    path('generate_attendance_month/',views.generate_attendance_month),
    path('parent_view_attendance/',views.parent_view_attendance),
    path('parent_attendance_month/',views.parent_attendance_month),
    path('parent_attendance_total/',views.parent_attendance_total),
    path('parent_attendance_subject/',views.parent_attendance_subject),
    path('parent_view_attendance/',views.parent_view_attendance),
    path('staff_attendance_total/',views.staff_attendance_total),
    path('staff_attendance_total_post/',views.staff_attendance_total_post),


]
